const data = {
  products: [
    {
      name: 'Birken Stock Sandals',
      slug: 'birken-stock-sandals',
      category: 'Sandals',
      image: 'images/S0.jpg',
      price: 'Ghc' + 150,
      countInStock: 10,
      brand: 'Harunzy Collection',
      rating: 4.5,
      numReviews: 10,
      description: 'The best sandals for everyday life',
    },
    {
      name: 'Birken Stock Sandals',
      slug: 'birken-stock-sandals',
      category: 'Sandals',
      image: 'images/S1.jpg',
      price: 'Ghc' + 150,
      countInStock: 8,
      brand: 'Harunzy Collection',
      rating: 4.5,
      numReviews: 10,
      description: 'The best sandals for everyday life',
    },
    {
      name: 'Birken Stock Sandals',
      slug: 'birken-stock-sandals',
      category: 'Sandals',
      image: 'images/S2.jpg',
      price: 'Ghc' + 150,
      countInStock: 6,
      brand: 'Harunzy Collection',
      rating: 4.5,
      numReviews: 10,
      description: 'The best sandals for everyday life',
    },
    {
      name: 'Birken Stock Sandals',
      slug: 'birken-stock-sandals',
      category: 'Sandals',
      image: 'images/S3.jpg',
      price: 'Ghc' + 150,
      countInStock: 4,
      brand: 'Harunzy Collection',
      rating: 4.5,
      numReviews: 10,
      description: 'The best sandals for everyday life',
    },
  ],
};

export default data;
